apiVersion: 1

deleteDatasources:
  - name: InfluxDB
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    database: mydb
    user: grafana
    password: grafana
    url: http://influxdb:8086