---
version: '3'
# Just a demo-setup, everything is ephemeral not for dev orproduction use

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock
    restart: always

  influxdb:
    image: influxdb:1.5-alpine
    container_name: influxdb
    environment:
        INFLUXDB_DB: mydb
    ports:
      - 8086:8086
    restart: always
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana_provisioning/:/etc/grafana/provisioning/
    depends_on:
      - influxdb
    restart: always

  node-red:
#    image: nodered/node-red
    build: ./node_red
    container_name: node-red
    volumes:
      - ./node_red_config/flows.json:/data/flows.json
    ports:
      - 1880:1880
    restart: always