---
version: '3'
# Just a demo-setup, everything is ephemeral not for dev orproduction use

services:
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: -H unix:///var/run/docker.sock
    restart: always
    networks:
      - backend

  influxdb:
    image: influxdb:1.5-alpine
    volumes:
      - influxdb-storage:/var/lib/influxdb
    restart: always
    networks:
      - backend
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - influxdb

  node-red:
    image: nodered/node-red:slim
    volumes:
      - ./data:/data
    ports:
      - 1880:1880
    restart: always
    networks:
      - backend

networks:
  backend:
